### ISSUE TITLE
support for MPT

### ISSUE THREAD

**Issue by 152334H** [explosion/curated-transformers#241]
title

**Comment by danieldk** [comment]
We'll look into it! We checked MPS support in combination with [`spacy-curated-transformers`](https://github.com/explosion/spacy-curated-transformers/). But it is possible that we broke something with the recent LLM additions.

**Comment by danieldk** [comment]
Oh, sorry, misread MPT as MPS. Our focus is on getting the 1.0.0 release out first, support for MPT is on our todo list after that.

**Comment by 152334H** [comment]
No problem!

**Comment by danieldk** [comment]
MPT will be supported in Curated Transformers 1.1.0. If there are no other show-stoppers, we plan to release 1.1.0 later this week.
