### ISSUE TITLE
Usage of deprecated `torch.norm`

### ISSUE THREAD

**Issue by kit1980** [explosion/curated-transformers#250]
`torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained.

Please follow https://pytorch.org/docs/stable/generated/torch.norm.html to update.

https://github.com/explosion/curated-transformers/blob/main/curated_transformers/layers/embeddings.py#L51C24-L51C28

**Comment by rmitsch** [comment]
Thanks for the heads-up! We'll look into it.
