### ISSUE TITLE
Decoupling weights downloading from loading

### ISSUE THREAD

**Issue by bilelomrani1** [explosion/curated-transformers#302]
First, thank you for open sourcing this library, I'm currently evaluating `curated-transformers` to assess if I can migrate from `transformers` to this more focused and lightweight library. One of the few things that I'm missing with `transformers` is a way to decouple model downloading from model loading. In a distributed training setting, we only want the weights to be cached on disk by a single process on each node, and then loaded from all the child processes. This is especially critical when the model is very large and cannot fit in a single device.

Currently, the following snippet downloads and loads the model

```python
encoder = BERTEncoder.from_hf_hub(
   name="bert-base-uncased",
   revision="main",
   device=torch.device("cuda", index=0),
)
```

I suggest (optionally) letting the user decouple downloading and loading with an API similar to this

```python
BERTEncoder.pull_from_hf_hub(name="bert-base-uncased", revision="main")
encoder = BERTEncoder.from_hf_hub(
   name="bert-base-uncased",
   revision="main",
   device=torch.device("cuda", index=0),
)
```

where the first line caches the weights on disk and the second one first checks the cache and only downloads when the cache misses.

Does it sound like a useful feature to you?

**Comment by danieldk** [comment]
Thanks for the feature request! This sounds like a very useful feature and would be simple to add. We'll add it to our todo list.

**Comment by honnibal** [comment]
If there's an easy way to also support loading from a byte string, I'd see that as desirable too 🙂 

I get that it might not be so easy though, depending on the way PyTorch does things.

**Comment by danieldk** [comment]
> If there's an easy way to also support loading from a byte string, I'd see that as desirable too 🙂
> 
> I get that it might not be so easy though, depending on the way PyTorch does things.

We could definitely support that. But we still need to hash out how we want to serialize the model hyperparameters (outside TorchScript/ONNX/etc.). What we had in mind now is generating configuration json that it compatible with HF transformers. We could then easily serialize the config + state dict to a byte string.

**Comment by danieldk** [comment]
@bilelomrani1 the `main` branch now supports this, so if you want to give it a spin:

https://curated-transformers.readthedocs.io/en/latest/encoders.html#curated_transformers.models.AutoEncoder.download_to_cache

**Comment by bilelomrani1** [comment]
Thank you @shadeMe @danieldk this works exactly as intended! I leave the issue open if you want to track the status for loading from a byte string here but feel free to close, as this solves my issue.

**Comment by danieldk** [comment]
Thanks for the suggestion and for testing 👍.
