### ISSUE TITLE
scipy through bitsandbytes

### ISSUE THREAD

**Issue by evelynmitchell** [explosion/curated-transformers#307]
The setup.cfg imports scipy because bitsandbytes used it, but didn't import it.

This issue now appears to be resolved in bitsandbytes:
https://github.com/TimDettmers/bitsandbytes/issues/544
https://github.com/TimDettmers/bitsandbytes/blob/main/requirements.txt

**Comment by shadeMe** [comment]
Hi, thanks for opening a PR for this. Unfortunately, the issue has yet to be fully resolved - As mentioned in the comments in https://github.com/TimDettmers/bitsandbytes/issues/544, `scipy` needs to also be added to the `install-requires` section of `setup.cfg` (or passed as the appropriate arg in `setup.py`).

So, we'll need to keep the extra requirement on our end for the time being. I'll go ahead and close this now, but feel free to re-open it once [this PR](https://github.com/TimDettmers/bitsandbytes/pull/525) has been merged upstream.
