### ISSUE TITLE
Loading a model saved locally

### ISSUE THREAD

**Issue by ccdv-ai** [explosion/curated-transformers#314]
Hi
I probably missed something but how do you load a model saved locally (e.g a fine tuned Llama model)?
I'm trying to use `AutoGenerator` but I cannot load a local model (hf format).

In the documentation it is stated that a model architecture is infered by the repo name, I guess there may be a conflict with a custom local name.

Thank you.

**Comment by shadeMe** [comment]
Currently, we only support loading models directly from the Hugging Face Hub. That being said, support for loading locally stored models is on our roadmap.
