### ISSUE TITLE
Pretrain from scratch and fine tune

### ISSUE THREAD

**Issue by nimitpattanasri** [explosion/curated-transformers#329]
Do you have an example of how to pretrain or fine tune a BERT model?

**Comment by danieldk** [comment]
We do provide an example on how to finetune a Curated Transformers model with spaCy:

https://github.com/explosion/spacy-curated-transformers/tree/main/project

We don't have examples for finetuning directly with Curated Transformers yet, but training is one of the aspects that we'll focus on in the upcoming period.
