### ISSUE TITLE
Register models/tokenizers through `catalogue`, so that the auto classes pick them up

### ISSUE THREAD

**Issue by danieldk** [explosion/curated-transformers#346]
The auto classes can currently support tokenizers and models from Curated Transformers. If they were registered through `catalogue`, we could support external models in the auto classes.

**Comment by Ryu1845** [comment]
Shouldn't this be closed, considering #351 ?

**Comment by danieldk** [comment]
I think we kept this open because we still want to move Falcon to an extras package. But that's also covered by #347. So yeah, let's close this one 👍.
